import type { VercelRequest, VercelResponse } from '@vercel/node';
import { ai, handleError } from './utils';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { prompt } = req.body;
    
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      res.status(200).json({ imageBase64: response.generatedImages[0].image.imageBytes });
      return;
    }

    if (response.promptFeedback?.blockReason) {
      throw new Error(`Your prompt was blocked due to: ${response.promptFeedback.blockReason}.`);
    }

    throw new Error('No image was generated by the AI.');
  } catch (error) {
    handleError(res, error, 'Failed to generate image.');
  }
}
